---
DBInfo:
  baseURL: http://cmslab3.spa.umn.edu/~cros0400/cgi-bin/WagonDB
  inserter: WagonDBInserter
  name: WagonDB
  reader: WagonDBReadUser
  use_database: False
GUIType: FlexCable
SerialCheckSafe: true
#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: <username>, hostname: <hostname>, remoteip: <remoteip>}
TestHandler: {name: ZMQ, localip: <localip>, remoteip: cmstester8, username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}
PhysicalTest: []
Test:
- TestClass: id_resist_test
  TestPath: /home/HGCAL_dev/FlexTest/FlexCableTesting
  TestScript: wagon_rtd.py
  desc_long: Must be completed after the general resistance measurement
  desc_short: Measure resistance of ID resistor
  name: ID Resistor Measurement
  required: 1
- TestClass: BERT
  TestPath: /home/HGCAL_dev/FlexTest/FlexCableTesting
  TestScript: run_bert.py
  desc_long: Needs to be completed after I2C check in order to set up wagon wheel
  desc_short: Determine quality of data transmission
  name: Bit Error Rate Test
  required: 1
UsingScanner: true

People: [Lauren, Billy]
...
