---
DBInfo:
  admin: FactoryInserter
  baseURL: http://cmslab1.spa.umn.edu/Factory/WagonDB
  inserter: FactoryInserter
  name: WagonDB_PRO
  reader: FactoryReadUser
  use_database: true
GUIType: Wagon
UsingScanner: true
SerialCheckSafe: true
#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: HGCAL_dev, hostname: "TEST_SERVER_IP_ADDRESS", remoteip: <remoteip>}
TestHandler: {name: ZMQ, localip: <localip>, remoteip: umn-zcu102-d, username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}

PhysicalTest: []
Test:
- TestClass: TestEconTtoEngine
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: test_econ_links.py
  desc_long: 
  desc_short: 
  name: ECON-T Elinks To Engine
  required: 1
- TestClass: TestEconTtoEngine
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: test_econ_links.py
  desc_long: 
  desc_short: 
  name: ECON-D Elinks To Engine
  required: 1
- TestClass: TestEconTtoEngine
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: test_econ_links.py
  desc_long: 
  desc_short: 
  name: ECON-T Elinks From Module
  required: 1
- TestClass: TestEconTtoEngine
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: test_econ_links.py
  desc_long: 
  desc_short: 
  name: ECON-D Elinks From Module
  required: 1
InspectionTest:
- TestClass: Inspection
  name: Inspection1
  required: 1
  checkboxes: 
    - {text: "Is the board bent?", value: False, requirement: False}
    - {text: "Is the board visibly broken?", value: False, requirement: False}
    - {text: "Are any components missing?", value: False, requirement: False}
    - {text: "Are any components visibly broken?", value: False, requirement: False}
  comments: No Comment
