---
DBInfo:
  admin: FactoryInserter
  baseURL: http://cmslab1.spa.umn.edu/Factory/WagonDB
  inserter: FactoryInserter
  name: WagonDB_PRO
  reader: FactoryReadUser
  use_database: true
GUIType: Wagon
SerialCheckSafe: true
#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: HGCAL_dev, hostname: "TEST_SERVER_IP_ADDRESS", remoteip: <remoteip>}
TestHandler: {name: ZMQ, localip: <localip>, remoteip: "TEST_SERVER_IP_ADDRESS", username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}
PhysicalTest: []
Test:
- TestClass: ADC
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_adc_self_test.py
  desc_long: Checking all ADCs to see if they are running as expected before running any tests
  desc_short: ADC interal test
  name: ADC Self Test
  required: 1
- TestClass: gen_resist_test
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: wagon_rtd.py
  desc_long: Test must be completed before attempting to measure ID resistor
  desc_short: Measure resistance of analog lines
  name: Resistance Measurement
  required: 1
- TestClass: id_resist_test
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: wagon_rtd.py
  desc_long: Must be completed after the general resistance measurement
  desc_short: Measure resistance of ID resistor
  name: ID Resistor Measurement
  required: 1
- TestClass: IIC_Check
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_iic_check.py
  desc_long: Test must be completed before BERT for wagon wheel configuration
  desc_short: Check I2C read/write along wagon
  name: I2C Read/Write
  required: 1
- TestClass: BERT
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_bert.py
  desc_long: Needs to be completed after I2C check in order to set up wagon wheel
  desc_short: Determine quality of data transmission
  name: Bit Error Rate Test
  required: 1
- TestClass: Mod4LMezzComm
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_mod4_tests.py
  desc_long: "LMezz LPGBT Comm"
  desc_short: "LMezz LPGBT Comm"
  name: "Mod4 LMezz Comm"
  required: 1
- TestClass: Mod4LMezzId
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_mod4_tests.py
  desc_long: "LMezz LPGBT Id"
  desc_short: "LMezz LPGBT Id"
  name: "Mod4 LMezz Id"
  required: 1
- TestClass: Mod4Resistance
  TestPath: /home/HGCAL_dev/sw/WagonTesting
  TestScript: run_mod4_tests.py
  desc_long: "Mod4 Resistance"
  desc_short: "Mod4 Resistance"
  name: "Mod4 Resistance"
  required: 1

UsingScanner: true
InspectionTest:
- TestClass: Inspection
  name: Inspection1
  required: 1
  checkboxes: 
    - {text: "Is the board bent?", value: False, requirement: False}
    - {text: "Is the board visibly broken?", value: False, requirement: False}
    - {text: "Are any components missing?", value: False, requirement: False}
    - {text: "Are any components visibly broken?", value: False, requirement: False}
  comments: No Comment
