---
DBInfo:
  admin: FactoryInserter
  baseURL: http://cmslab1.spa.umn.edu/Factory/WagonDB
  inserter: FactoryInserter
  name: WagonDB_PRO
  reader: FactoryReadUser
  use_database: false

People:
  - Adrian
  - Charlie

GUIType: Wagon
SerialCheckSafe: false
UsingScanner: True

#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: HGCAL_dev, hostname: "TEST_SERVER_IP_ADDRESS", remoteip: <remoteip>}
TestHandler: {name: ZMQ, localip: <localip>, remoteip: "192.168.140.147", username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}

PhysicalTest: []

Test:
- TestClass: GPIOTest
  TestPath: /home/hgcaldev/WagonTesting/MezzTest
  TestScript: gpio_test.py
  desc_long: Check that GPIO lines are working
  desc_short: Check GPIO
  name: GPIO Test
  required: 1
- TestClass: ADCTest
  TestPath: /home/hgcaldev/WagonTesting/MezzTest
  TestScript: adc_test.py
  desc_long: Check that ADC lines are working
  desc_short: Check ADC
  name: ADC Test
  required: 1

